---


'.review':
  before_script:
    - 'python -m pip install tox'
  script:
    - 'export TOXENV="${CI_JOB_NAME##review}"'
    - 'python -m tox'
    - 'python -m tox -e package'

'review py3.8':
  extends: '.review'
  image: 'python:3.8'

'review py3.9':
  extends: '.review'
  image: 'python:3.9'

'review py3.10':
  extends: '.review'
  image: 'python:3.10'

'review py3.11':
  extends: '.review'
  image: 'python:3.11'

'review py3.12':
  allow_failure: true
  extends: '.review'
  image: 'python:3.12-rc'


...  # EOF
